@startuml

class Mascota 
{
    - vida : int
    + Comer (alimento:Alimento)
    + Jugar ()
    + Cagar ()
    + Duchar ()
    + Enfermar ()
    + Dormir ()
}

class Alimento
{
    - energia : int
    + ExtraerEnergia ()
}

Mascota o-- Alimento
@enduml